steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:1.01', '.']
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    # args: ['push', 'gcr.io/$PROJECT_ID/docker-repo']
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:1.01']
    # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'karira-server',
        '--image',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:1.01',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--cpu',
        '2',
        '--memory',
        '4Gi',
        '--port',
        '8000',
      ]

options:
  logging: CLOUD_LOGGING_ONLY