steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:$COMMIT_SHA', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:latest', './server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/recommendation:$COMMIT_SHA', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/recommendation:latest', './recommendation']
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/recommendation']
    # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'karira-server',
        '--image',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/server:latest',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--cpu',
        '2',
        '--memory',
        '4Gi',
        '--port',
        '8000',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'karira-recommendation',
        '--image',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/docker-karira/recommendation:latest',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--cpu',
        '2',
        '--memory',
        '4Gi',
        '--port',
        '8000',
      ]
options:
  logging: CLOUD_LOGGING_ONLY