version: "3"

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - docker-prod.env
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: