FROM python:3.7-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set up the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .
COPY browse_project_model /app/browse_project_model/my_model  

# Add this line to copy the model file

# Expose the application port
EXPOSE 5000

# Start the application
CMD ["python3", "app.py"]
